const Tone = window.Tone;

export function getToneMonoSynth(synthPreset) {
  const arr = synthPreset.split(':');
  const synth = arr[0];
  const preset = arr[1];
  return new Tone[synth](preset ? ToneMonoSynths[synth][preset] : '');
}

const ToneMonoSynths = {
  FMSynth: {
    ElectricCello: {
      harmonicity: 3.01,
      modulationIndex: 14,
      oscillator: {
        type: 'triangle',
      },
      envelope: {
        attack: 0.2,
        decay: 0.3,
        sustain: 0.1,
        release: 1.2,
      },
      modulation: {
        type: 'square',
      },
      modulationEnvelope: {
        attack: 0.01,
        decay: 0.5,
        sustain: 0.2,
        release: 0.1,
      },
    },

    Kalimba: {
      harmonicity: 8,
      modulationIndex: 2,
      oscillator: {
        type: 'sine',
      },
      envelope: {
        attack: 0.001,
        decay: 2,
        sustain: 0.1,
        release: 2,
      },
      modulation: {
        type: 'square',
      },
      modulationEnvelope: {
        attack: 0.002,
        decay: 0.2,
        sustain: 0,
        release: 0.2,
      },
    },

    ThinSaws: {
      harmonicity: 0.5,
      modulationIndex: 1.2,
      oscillator: {
        type: 'fmsawtooth',
        modulationType: 'sine',
        modulationIndex: 20,
        harmonicity: 3,
      },
      envelope: {
        attack: 0.05,
        decay: 0.3,
        sustain: 0.1,
        release: 1.2,
      },
      modulation: {
        volume: 0,
        type: 'triangle',
      },
      modulationEnvelope: {
        attack: 0.35,
        decay: 0.1,
        sustain: 1,
        release: 0.01,
      },
    },
  },

  MonoSynth: {
    BassGuitar: {
      oscillator: {
        type: 'fmsquare5',
        modulationType: 'triangle',
        modulationIndex: 2,
        harmonicity: 0.501,
      },
      filter: {
        Q: 1,
        type: 'lowpass',
        rolloff: -24,
      },
      envelope: {
        attack: 0.01,
        decay: 0.1,
        sustain: 0.4,
        release: 2,
      },
      filterEnvelope: {
        attack: 0.01,
        decay: 0.1,
        sustain: 0.8,
        release: 1.5,
        baseFrequency: 50,
        octaves: 4.4,
      },
    },
    BrassCircuit: {
      portamento: 0.01,
      oscillator: {
        type: 'sawtooth',
      },
      filter: {
        Q: 2,
        type: 'lowpass',
        rolloff: -24,
      },
      envelope: {
        attack: 0.1,
        decay: 0.1,
        sustain: 0.6,
        release: 0.5,
      },
      filterEnvelope: {
        attack: 0.05,
        decay: 0.8,
        sustain: 0.4,
        release: 1.5,
        baseFrequency: 2000,
        octaves: 1.5,
      },
    },

    Pianoetta: {
      oscillator: {
        type: 'square',
      },
      filter: {
        Q: 2,
        type: 'lowpass',
        rolloff: -12,
      },
      envelope: {
        attack: 0.005,
        decay: 3,
        sustain: 0,
        release: 0.45,
      },
      filterEnvelope: {
        attack: 0.001,
        decay: 0.32,
        sustain: 0.9,
        release: 3,
        baseFrequency: 700,
        octaves: 2.3,
      },
    },

    Pizz: {
      oscillator: {
        type: 'sawtooth',
      },
      filter: {
        Q: 3,
        type: 'highpass',
        rolloff: -12,
      },
      envelope: {
        attack: 0.01,
        decay: 0.3,
        sustain: 0,
        release: 0.9,
      },
      filterEnvelope: {
        attack: 0.01,
        decay: 0.1,
        sustain: 0,
        release: 0.1,
        baseFrequency: 800,
        octaves: -1.2,
      },
    },
  },

  NoiseSynth: {
    Gravel: {
      noise: {
        type: 'pink',
        playbackRate: 0.1,
      },
      envelope: {
        attack: 0.5,
        decay: 2,
        sustain: 0.5,
        release: 3,
      },
    },

    Train: {
      noise: {
        type: 'pink',
        playbackRate: 0.2,
      },
      envelope: {
        attackCurve: 'ripple',
        releaseCurve: 'ripple',
        attack: 1,
        decay: 0.3,
        sustain: 1,
        release: 1,
      },
    },
  },

  Synth: {
    Lectric: {
      portamento: 0.2,
      oscillator: {
        type: 'sawtooth',
      },
      envelope: {
        attack: 0.03,
        decay: 0.1,
        sustain: 0.2,
        release: 0.02,
      },
    },
    Marimba: {
      oscillator: {
        partials: [1, 0, 2, 0, 3],
      },
      envelope: {
        attack: 0.001,
        decay: 1.2,
        sustain: 0,
        release: 1.2,
      },
    },
    Steelpan: {
      oscillator: {
        type: 'fatcustom',
        partials: [0.2, 1, 0, 0.5, 0.1],
        spread: 40,
        count: 3,
      },
      envelope: {
        attack: 0.001,
        decay: 1.6,
        sustain: 0,
        release: 1.6,
      },
    },
    SuperSaw: {
      oscillator: {
        type: 'fatsawtooth',
        count: 4,
        spread: 30,
      },
      envelope: {
        attack: 0.01,
        decay: 0.1,
        sustain: 0.5,
        release: 0.4,
        attackCurve: 'exponential',
      },
    },
  },
};

export const samplers = {
  piano: {
    C3: '/sounds/samplers/piano/piano48.wav',
    Db3: '/sounds/samplers/piano/piano49.wav',
    D3: '/sounds/samplers/piano/piano50.wav',
    Eb3: '/sounds/samplers/piano/piano51.wav',
    E3: '/sounds/samplers/piano/piano52.wav',
    F3: '/sounds/samplers/piano/piano53.wav',
    Gb3: '/sounds/samplers/piano/piano54.wav',
    G3: '/sounds/samplers/piano/piano55.wav',
    Ab3: '/sounds/samplers/piano/piano56.wav',
    A4: '/sounds/samplers/piano/piano57.wav',
    Bb4: '/sounds/samplers/piano/piano58.wav',
    B4: '/sounds/samplers/piano/piano59.wav',
    C4: '/sounds/samplers/piano/piano60.wav',
    Db4: '/sounds/samplers/piano/piano61.wav',
    D4: '/sounds/samplers/piano/piano62.wav',
    Eb4: '/sounds/samplers/piano/piano63.wav',
    E4: '/sounds/samplers/piano/piano64.wav',
    F4: '/sounds/samplers/piano/piano65.wav',
    Gb4: '/sounds/samplers/piano/piano66.wav',
    G4: '/sounds/samplers/piano/piano67.wav',
    Ab4: '/sounds/samplers/piano/piano68.wav',
    A5: '/sounds/samplers/piano/piano69.wav',
    Bb5: '/sounds/samplers/piano/piano70.wav',
    B5: '/sounds/samplers/piano/piano71.wav',
    C5: '/sounds/samplers/piano/piano72.wav',
    Db5: '/sounds/samplers/piano/piano73.wav',
    D5: '/sounds/samplers/piano/piano74.wav',
    Eb5: '/sounds/samplers/piano/piano75.wav',
    E5: '/sounds/samplers/piano/piano76.wav',
    F5: '/sounds/samplers/piano/piano77.wav',
    Gb5: '/sounds/samplers/piano/piano78.wav',
    G5: '/sounds/samplers/piano/piano79.wav',
    Ab5: '/sounds/samplers/piano/piano80.wav',
    A6: '/sounds/samplers/piano/piano81.wav',
    Bb6: '/sounds/samplers/piano/piano82.wav',
    B6: '/sounds/samplers/piano/piano83.wav',
  },
  superSaw: {
    C3: '/sounds/samplers/superSaw/C3.wav',
    Db3: '/sounds/samplers/superSaw/Db3.wav',
    D3: '/sounds/samplers/superSaw/D3.wav',
    Eb3: '/sounds/samplers/superSaw/Eb3.wav',
    E3: '/sounds/samplers/superSaw/E3.wav',
    F3: '/sounds/samplers/superSaw/F3.wav',
    Gb3: '/sounds/samplers/superSaw/Gb3.wav',
    G3: '/sounds/samplers/superSaw/G3.wav',
    Ab3: '/sounds/samplers/superSaw/Ab3.wav',
    A4: '/sounds/samplers/superSaw/A4.wav',
    Bb4: '/sounds/samplers/superSaw/Bb4.wav',
    B4: '/sounds/samplers/superSaw/B4.wav',
    C4: '/sounds/samplers/superSaw/C4.wav',
    Db4: '/sounds/samplers/superSaw/Db4.wav',
    D4: '/sounds/samplers/superSaw/D4.wav',
    Eb4: '/sounds/samplers/superSaw/Eb4.wav',
    E4: '/sounds/samplers/superSaw/E4.wav',
    F4: '/sounds/samplers/superSaw/F4.wav',
    Gb4: '/sounds/samplers/superSaw/Gb4.wav',
    G4: '/sounds/samplers/superSaw/G4.wav',
    Ab4: '/sounds/samplers/superSaw/Ab4.wav',
    A5: '/sounds/samplers/superSaw/A5.wav',
    Bb5: '/sounds/samplers/superSaw/Bb5.wav',
    B5: '/sounds/samplers/superSaw/B5.wav',
    C5: '/sounds/samplers/superSaw/C5.wav',
    Db5: '/sounds/samplers/superSaw/Db5.wav',
    D5: '/sounds/samplers/superSaw/D5.wav',
    Eb5: '/sounds/samplers/superSaw/Eb5.wav',
    E5: '/sounds/samplers/superSaw/E5.wav',
    F5: '/sounds/samplers/superSaw/F5.wav',
    Gb5: '/sounds/samplers/superSaw/Gb5.wav',
    G5: '/sounds/samplers/superSaw/G5.wav',
    Ab5: '/sounds/samplers/superSaw/Ab5.wav',
    A6: '/sounds/samplers/superSaw/A6.wav',
    Bb6: '/sounds/samplers/superSaw/Bb6.wav',
    B6: '/sounds/samplers/superSaw/B6.wav',
    C6: '/sounds/samplers/superSaw/C6.wav',
  },

  korgBass: {
    a1: '/sounds/samplers/korgBass/a1-33.wav',
    a2: '/sounds/samplers/korgBass/a2-45.wav',
    a3: '/sounds/samplers/korgBass/a3-57.wav',
    a4: '/sounds/samplers/korgBass/a4-69.wav',
    a5: '/sounds/samplers/korgBass/a5-81.wav',
    a6: '/sounds/samplers/korgBass/a6-93.wav',
    b1: '/sounds/samplers/korgBass/b1-35.wav',
    b2: '/sounds/samplers/korgBass/b2-47.wav',
    b3: '/sounds/samplers/korgBass/b3-59.wav',
    b4: '/sounds/samplers/korgBass/b4-71.wav',
    b5: '/sounds/samplers/korgBass/b5-83.wav',
    b6: '/sounds/samplers/korgBass/b6-95.wav',
    bb1: '/sounds/samplers/korgBass/bb1-34.wav',
    bb2: '/sounds/samplers/korgBass/bb2-46.wav',
    bb3: '/sounds/samplers/korgBass/bb3-58.wav',
    bb4: '/sounds/samplers/korgBass/bb4-70.wav',
    bb5: '/sounds/samplers/korgBass/bb5-82.wav',
    bb6: '/sounds/samplers/korgBass/bb6-94.wav',
    c1: '/sounds/samplers/korgBass/c1-24.wav',
    c2: '/sounds/samplers/korgBass/c2-36.wav',
    c3: '/sounds/samplers/korgBass/c3-48.wav',
    c4: '/sounds/samplers/korgBass/c4-60.wav',
    c5: '/sounds/samplers/korgBass/c5-72.wav',
    c6: '/sounds/samplers/korgBass/c6-84.wav',
    c7: '/sounds/samplers/korgBass/c7-96.wav',
    d1: '/sounds/samplers/korgBass/d1-26.wav',
    d2: '/sounds/samplers/korgBass/d2-38.wav',
    d3: '/sounds/samplers/korgBass/d3-50.wav',
    d4: '/sounds/samplers/korgBass/d4-62.wav',
    d5: '/sounds/samplers/korgBass/d5-74.wav',
    d6: '/sounds/samplers/korgBass/d6-86.wav',
    db1: '/sounds/samplers/korgBass/db1-25.wav',
    db2: '/sounds/samplers/korgBass/db2-37.wav',
    db3: '/sounds/samplers/korgBass/db3-49.wav',
    db4: '/sounds/samplers/korgBass/db4-61.wav',
    db5: '/sounds/samplers/korgBass/db5-73.wav',
    db6: '/sounds/samplers/korgBass/db6-85.wav',
    e1: '/sounds/samplers/korgBass/e1-28.wav',
    e2: '/sounds/samplers/korgBass/e2-40.wav',
    e3: '/sounds/samplers/korgBass/e3-52.wav',
    e4: '/sounds/samplers/korgBass/e4-64.wav',
    e5: '/sounds/samplers/korgBass/e5-76.wav',
    e6: '/sounds/samplers/korgBass/e6-88.wav',
    eb1: '/sounds/samplers/korgBass/eb1-27.wav',
    eb2: '/sounds/samplers/korgBass/eb2-39.wav',
    eb3: '/sounds/samplers/korgBass/eb3-51.wav',
    eb4: '/sounds/samplers/korgBass/eb4-63.wav',
    eb5: '/sounds/samplers/korgBass/eb5-75.wav',
    eb6: '/sounds/samplers/korgBass/eb6-87.wav',
    f1: '/sounds/samplers/korgBass/f1-30.wav',
    f2: '/sounds/samplers/korgBass/f2-42.wav',
    f3: '/sounds/samplers/korgBass/f3-54.wav',
    f4: '/sounds/samplers/korgBass/f4-66.wav',
    f5: '/sounds/samplers/korgBass/f5-78.wav',
    f6: '/sounds/samplers/korgBass/f6-90.wav',
    g1: '/sounds/samplers/korgBass/g1-32.wav',
    g2: '/sounds/samplers/korgBass/g2-44.wav',
    g3: '/sounds/samplers/korgBass/g3-56.wav',
    g4: '/sounds/samplers/korgBass/g4-68.wav',
    g5: '/sounds/samplers/korgBass/g5-80.wav',
    g6: '/sounds/samplers/korgBass/g6-92.wav',
    gb1: '/sounds/samplers/korgBass/gb1-31.wav',
    gb2: '/sounds/samplers/korgBass/gb2-43.wav',
    gb3: '/sounds/samplers/korgBass/gb3-55.wav',
    gb4: '/sounds/samplers/korgBass/gb4-67.wav',
    gb5: '/sounds/samplers/korgBass/gb5-79.wav',
    gb6: '/sounds/samplers/korgBass/gb6-91.wav',
  },

  ciriusRez: {
    a3: '/sounds/samplers/ciriusRez/a3.wav',
    a4: '/sounds/samplers/ciriusRez/a4.wav',
    b3: '/sounds/samplers/ciriusRez/b3.wav',
    b4: '/sounds/samplers/ciriusRez/b4.wav',
    bb3: '/sounds/samplers/ciriusRez/bb3.wav',
    bb4: '/sounds/samplers/ciriusRez/bb4.wav',
    c3: '/sounds/samplers/ciriusRez/c3.wav',
    c4: '/sounds/samplers/ciriusRez/c4.wav',
    d3: '/sounds/samplers/ciriusRez/d3.wav',
    d4: '/sounds/samplers/ciriusRez/d4.wav',
    db3: '/sounds/samplers/ciriusRez/db3.wav',
    db4: '/sounds/samplers/ciriusRez/db4.wav',
    e3: '/sounds/samplers/ciriusRez/e3.wav',
    e4: '/sounds/samplers/ciriusRez/e4.wav',
    eb3: '/sounds/samplers/ciriusRez/eb3.wav',
    eb4: '/sounds/samplers/ciriusRez/eb4.wav',
    f3: '/sounds/samplers/ciriusRez/f3.wav',
    f4: '/sounds/samplers/ciriusRez/f4.wav',
    g3: '/sounds/samplers/ciriusRez/g3.wav',
    g4: '/sounds/samplers/ciriusRez/g4.wav',
    gb3: '/sounds/samplers/ciriusRez/gb3.wav',
    gb4: '/sounds/samplers/ciriusRez/gb4.wav',
  },

  celestialPad: {
    a3: '/sounds/samplers/celestialPad/a3.wav',
    a4: '/sounds/samplers/celestialPad/a4.wav',
    b3: '/sounds/samplers/celestialPad/b3.wav',
    b4: '/sounds/samplers/celestialPad/b4.wav',
    bb3: '/sounds/samplers/celestialPad/bb3.wav',
    bb4: '/sounds/samplers/celestialPad/bb4.wav',
    c3: '/sounds/samplers/celestialPad/c3.wav',
    c4: '/sounds/samplers/celestialPad/c4.wav',
    c5: '/sounds/samplers/celestialPad/c5.wav',
    d3: '/sounds/samplers/celestialPad/d3.wav',
    d4: '/sounds/samplers/celestialPad/d4.wav',
    db3: '/sounds/samplers/celestialPad/db3.wav',
    db4: '/sounds/samplers/celestialPad/db4.wav',
    e3: '/sounds/samplers/celestialPad/e3.wav',
    e4: '/sounds/samplers/celestialPad/e4.wav',
    eb3: '/sounds/samplers/celestialPad/eb3.wav',
    eb4: '/sounds/samplers/celestialPad/eb4.wav',
    f3: '/sounds/samplers/celestialPad/f3.wav',
    f4: '/sounds/samplers/celestialPad/f4.wav',
    g3: '/sounds/samplers/celestialPad/g3.wav',
    g4: '/sounds/samplers/celestialPad/g4.wav',
    gb3: '/sounds/samplers/celestialPad/gb3.wav',
    gb4: '/sounds/samplers/celestialPad/gb4.wav',
  },
  epicTranceLead: {
    a3: '/sounds/samplers/epicTranceLead/a3.wav',
    a4: '/sounds/samplers/epicTranceLead/a4.wav',
    b3: '/sounds/samplers/epicTranceLead/b3.wav',
    b4: '/sounds/samplers/epicTranceLead/b4.wav',
    bb3: '/sounds/samplers/epicTranceLead/bb3.wav',
    bb4: '/sounds/samplers/epicTranceLead/bb4.wav',
    c3: '/sounds/samplers/epicTranceLead/c3.wav',
    c4: '/sounds/samplers/epicTranceLead/c4.wav',
    c5: '/sounds/samplers/epicTranceLead/c5.wav',
    d3: '/sounds/samplers/epicTranceLead/d3.wav',
    d4: '/sounds/samplers/epicTranceLead/d4.wav',
    db3: '/sounds/samplers/epicTranceLead/db3.wav',
    db4: '/sounds/samplers/epicTranceLead/db4.wav',
    e3: '/sounds/samplers/epicTranceLead/e3.wav',
    e4: '/sounds/samplers/epicTranceLead/e4.wav',
    eb3: '/sounds/samplers/epicTranceLead/eb3.wav',
    eb4: '/sounds/samplers/epicTranceLead/eb4.wav',
    f3: '/sounds/samplers/epicTranceLead/f3.wav',
    f4: '/sounds/samplers/epicTranceLead/f4.wav',
    g3: '/sounds/samplers/epicTranceLead/g3.wav',
    g4: '/sounds/samplers/epicTranceLead/g4.wav',
    gb3: '/sounds/samplers/epicTranceLead/gb3.wav',
    gb4: '/sounds/samplers/epicTranceLead/gb4.wav',
  },

  jarblePerator: {
    a3: '/sounds/samplers/jarblePerator/a3.wav',
    a4: '/sounds/samplers/jarblePerator/a4.wav',
    b3: '/sounds/samplers/jarblePerator/b3.wav',
    b4: '/sounds/samplers/jarblePerator/b4.wav',
    bb3: '/sounds/samplers/jarblePerator/bb3.wav',
    bb4: '/sounds/samplers/jarblePerator/bb4.wav',
    c3: '/sounds/samplers/jarblePerator/c3.wav',
    c4: '/sounds/samplers/jarblePerator/c4.wav',
    d3: '/sounds/samplers/jarblePerator/d3.wav',
    d4: '/sounds/samplers/jarblePerator/d4.wav',
    db3: '/sounds/samplers/jarblePerator/db3.wav',
    db4: '/sounds/samplers/jarblePerator/db4.wav',
    e3: '/sounds/samplers/jarblePerator/e3.wav',
    e4: '/sounds/samplers/jarblePerator/e4.wav',
    eb3: '/sounds/samplers/jarblePerator/eb3.wav',
    eb4: '/sounds/samplers/jarblePerator/eb4.wav',
    f3: '/sounds/samplers/jarblePerator/f3.wav',
    f4: '/sounds/samplers/jarblePerator/f4.wav',
    g3: '/sounds/samplers/jarblePerator/g3.wav',
    g4: '/sounds/samplers/jarblePerator/g4.wav',
    gb3: '/sounds/samplers/jarblePerator/gb3.wav',
    gb4: '/sounds/samplers/jarblePerator/gb4.wav',
  },

  psyTranceBass: {
    a1: '/sounds/samplers/psyTranceBass/a1.wav',
    a2: '/sounds/samplers/psyTranceBass/a2.wav',
    b1: '/sounds/samplers/psyTranceBass/b1.wav',
    b2: '/sounds/samplers/psyTranceBass/b2.wav',
    bb1: '/sounds/samplers/psyTranceBass/bb1.wav',
    bb2: '/sounds/samplers/psyTranceBass/bb2.wav',
    c1: '/sounds/samplers/psyTranceBass/c1.wav',
    c2: '/sounds/samplers/psyTranceBass/c2.wav',
    d1: '/sounds/samplers/psyTranceBass/d1.wav',
    d2: '/sounds/samplers/psyTranceBass/d2.wav',
    db1: '/sounds/samplers/psyTranceBass/db1.wav',
    db2: '/sounds/samplers/psyTranceBass/db2.wav',
    e1: '/sounds/samplers/psyTranceBass/e1.wav',
    e2: '/sounds/samplers/psyTranceBass/e2.wav',
    eb1: '/sounds/samplers/psyTranceBass/eb1.wav',
    eb2: '/sounds/samplers/psyTranceBass/eb2.wav',
    f1: '/sounds/samplers/psyTranceBass/f1.wav',
    f2: '/sounds/samplers/psyTranceBass/f2.wav',
    g1: '/sounds/samplers/psyTranceBass/g1.wav',
    g2: '/sounds/samplers/psyTranceBass/g2.wav',
    gb1: '/sounds/samplers/psyTranceBass/gb1.wav',
    gb2: '/sounds/samplers/psyTranceBass/gb2.wav',
  },
  clickBass: {
    A2: '/sounds/samplers/clickBass/A.wav',
    Ab2: '/sounds/samplers/clickBass/Ab.wav',
    B2: '/sounds/samplers/clickBass/B.wav',
    Bb2: '/sounds/samplers/clickBass/Bb.wav',
    C1: '/sounds/samplers/clickBass/C.wav',
    D1: '/sounds/samplers/clickBass/D.wav',
    Db1: '/sounds/samplers/clickBass/Db.wav',
    E1: '/sounds/samplers/clickBass/E.wav',
    Eb1: '/sounds/samplers/clickBass/Eb.wav',
    F1: '/sounds/samplers/clickBass/F.wav',
    G1: '/sounds/samplers/clickBass/G.wav',
    Gb1: '/sounds/samplers/clickBass/Gb.wav',
  },
  mechaBass1: {
    A1: '/sounds/samplers/mechaBass1/A1.WAV',
    A2: '/sounds/samplers/mechaBass1/A2.WAV',
    A3: '/sounds/samplers/mechaBass1/A3.WAV',
    B1: '/sounds/samplers/mechaBass1/B1.WAV',
    B2: '/sounds/samplers/mechaBass1/B2.WAV',
    B3: '/sounds/samplers/mechaBass1/B3.WAV',
    Bb1: '/sounds/samplers/mechaBass1/Bb1.WAV',
    Bb2: '/sounds/samplers/mechaBass1/Bb2.WAV',
    Bb3: '/sounds/samplers/mechaBass1/Bb3.WAV',
    C1: '/sounds/samplers/mechaBass1/C1.WAV',
    C2: '/sounds/samplers/mechaBass1/C2.WAV',
    C3: '/sounds/samplers/mechaBass1/C3.WAV',
    D1: '/sounds/samplers/mechaBass1/D1.WAV',
    D2: '/sounds/samplers/mechaBass1/D2.WAV',
    D3: '/sounds/samplers/mechaBass1/D3.WAV',
    Db1: '/sounds/samplers/mechaBass1/Db1.WAV',
    Db2: '/sounds/samplers/mechaBass1/Db2.WAV',
    Db3: '/sounds/samplers/mechaBass1/Db3.WAV',
    E1: '/sounds/samplers/mechaBass1/E1.WAV',
    E2: '/sounds/samplers/mechaBass1/E2.WAV',
    E3: '/sounds/samplers/mechaBass1/E3.WAV',
    Eb1: '/sounds/samplers/mechaBass1/Eb1.WAV',
    Eb2: '/sounds/samplers/mechaBass1/Eb2.WAV',
    Eb3: '/sounds/samplers/mechaBass1/Eb3.WAV',
    F1: '/sounds/samplers/mechaBass1/F1.WAV',
    F2: '/sounds/samplers/mechaBass1/F2.WAV',
    F3: '/sounds/samplers/mechaBass1/F3.WAV',
    G1: '/sounds/samplers/mechaBass1/G1.WAV',
    G2: '/sounds/samplers/mechaBass1/G2.WAV',
    G3: '/sounds/samplers/mechaBass1/G3.WAV',
    Gb1: '/sounds/samplers/mechaBass1/Gb1.WAV',
    Gb2: '/sounds/samplers/mechaBass1/Gb2.WAV',
    Gb3: '/sounds/samplers/mechaBass1/Gb3.WAV',
  },

  mechaBass2: {
    A1: '/sounds/samplers/mechaBass2/A1.WAV',
    A2: '/sounds/samplers/mechaBass2/A2.WAV',
    A3: '/sounds/samplers/mechaBass2/A3.WAV',
    B1: '/sounds/samplers/mechaBass2/B1.WAV',
    B2: '/sounds/samplers/mechaBass2/B2.WAV',
    B3: '/sounds/samplers/mechaBass2/B3.WAV',
    Bb1: '/sounds/samplers/mechaBass2/Bb1.WAV',
    Bb2: '/sounds/samplers/mechaBass2/Bb2.WAV',
    Bb3: '/sounds/samplers/mechaBass2/Bb3.WAV',
    C1: '/sounds/samplers/mechaBass2/C1.WAV',
    C2: '/sounds/samplers/mechaBass2/C2.WAV',
    C3: '/sounds/samplers/mechaBass2/C3.WAV',
    D1: '/sounds/samplers/mechaBass2/D1.WAV',
    D2: '/sounds/samplers/mechaBass2/D2.WAV',
    D3: '/sounds/samplers/mechaBass2/D3.WAV',
    Db1: '/sounds/samplers/mechaBass2/Db1.WAV',
    Db2: '/sounds/samplers/mechaBass2/Db2.WAV',
    Db3: '/sounds/samplers/mechaBass2/Db3.WAV',
    E1: '/sounds/samplers/mechaBass2/E1.WAV',
    E2: '/sounds/samplers/mechaBass2/E2.WAV',
    E3: '/sounds/samplers/mechaBass2/E3.WAV',
    Eb1: '/sounds/samplers/mechaBass2/Eb1.WAV',
    Eb2: '/sounds/samplers/mechaBass2/Eb2.WAV',
    Eb3: '/sounds/samplers/mechaBass2/Eb3.WAV',
    F1: '/sounds/samplers/mechaBass2/F1.WAV',
    F2: '/sounds/samplers/mechaBass2/F2.WAV',
    F3: '/sounds/samplers/mechaBass2/F3.WAV',
    G1: '/sounds/samplers/mechaBass2/G1.WAV',
    G2: '/sounds/samplers/mechaBass2/G2.WAV',
    G3: '/sounds/samplers/mechaBass2/G3.WAV',
    Gb1: '/sounds/samplers/mechaBass2/Gb1.WAV',
    Gb2: '/sounds/samplers/mechaBass2/Gb2.WAV',
    Gb3: '/sounds/samplers/mechaBass2/Gb3.WAV',
  },

  mechaBass3: {
    A1: '/sounds/samplers/mechaBass3/A1.WAV',
    A2: '/sounds/samplers/mechaBass3/A2.WAV',
    A3: '/sounds/samplers/mechaBass3/A3.WAV',
    B1: '/sounds/samplers/mechaBass3/B1.WAV',
    B2: '/sounds/samplers/mechaBass3/B2.WAV',
    B3: '/sounds/samplers/mechaBass3/B3.WAV',
    Bb1: '/sounds/samplers/mechaBass3/Bb1.WAV',
    Bb2: '/sounds/samplers/mechaBass3/Bb2.WAV',
    Bb3: '/sounds/samplers/mechaBass3/Bb3.WAV',
    C1: '/sounds/samplers/mechaBass3/C1.WAV',
    C2: '/sounds/samplers/mechaBass3/C2.WAV',
    C3: '/sounds/samplers/mechaBass3/C3.WAV',
    D1: '/sounds/samplers/mechaBass3/D1.WAV',
    D2: '/sounds/samplers/mechaBass3/D2.WAV',
    D3: '/sounds/samplers/mechaBass3/D3.WAV',
    Db1: '/sounds/samplers/mechaBass3/Db1.WAV',
    Db2: '/sounds/samplers/mechaBass3/Db2.WAV',
    Db3: '/sounds/samplers/mechaBass3/Db3.WAV',
    E1: '/sounds/samplers/mechaBass3/E1.WAV',
    E2: '/sounds/samplers/mechaBass3/E2.WAV',
    E3: '/sounds/samplers/mechaBass3/E3.WAV',
    Eb1: '/sounds/samplers/mechaBass3/Eb1.WAV',
    Eb2: '/sounds/samplers/mechaBass3/Eb2.WAV',
    Eb3: '/sounds/samplers/mechaBass3/Eb3.WAV',
    F1: '/sounds/samplers/mechaBass3/F1.WAV',
    F2: '/sounds/samplers/mechaBass3/F2.WAV',
    F3: '/sounds/samplers/mechaBass3/F3.WAV',
    G1: '/sounds/samplers/mechaBass3/G1.WAV',
    G2: '/sounds/samplers/mechaBass3/G2.WAV',
    G3: '/sounds/samplers/mechaBass3/G3.WAV',
    Gb1: '/sounds/samplers/mechaBass3/Gb1.WAV',
    Gb2: '/sounds/samplers/mechaBass3/Gb2.WAV',
    Gb3: '/sounds/samplers/mechaBass3/Gb3.WAV',
    Ab1: '/sounds/samplers/mechaBass3/Ab1.WAV',
    Ab2: '/sounds/samplers/mechaBass3/Ab2.WAV',
    Ab3: '/sounds/samplers/mechaBass3/Ab3.WAV',
  },
};
